export enum District {
  centralAndWestern = 'CENTRAL_AND_WESTERN',
  eastern = 'EASTERN',
  southern = 'SOUTHERN',
  wanChai = 'WAN_CHAI',
  shamShuiPo = 'SHAM_SHUI_PO',
  kowloonCity = 'KOWLOON_CITY',
  kwunTong = 'KWUN_TONG',
  wongTaiSin = 'WONG_TAI_SIN',
  yauTsimMong = 'YAU_TSIM_MONG',
  islands = 'ISLANDS',
  kwaiTsing = 'KWAI_TSING',
  north = 'NORTH',
  saiKung = 'SAI_KUNG',
  shaTin = 'SHA_TIN',
  taiPo = 'TAI_PO',
  tsuenWan = 'TSUEN_WAN',
  tuenMun = 'TUEN_MUN',
  yuenLong = 'YUEN_LONG'
}
